### PR TITLE
 Add support for Inline_query and more.

### PR DESCRIPTION
**Pull request by MatthiasHunziker**
Add support for inline_query, edited_message, channel_post, edited_channel_post.

### CODE REVIEW

**Comment by windkh** [comment]
Fitst of all thanks for the effort you took when creating this pullrequest.
I only had a quick look at your changes right now:
- maybe line 570 is wrong. I think the off call needs this.event instead of the callbackquery string
- will this break existing flows when upgrading?
I will try outyur changes soon...

**Comment by MatthiasHunziker** [comment]
Thanks for your quick reply.

• Yes that could be right. It would fit better with line 464

•

**Comment by MatthiasHunziker** [comment]
Thanks for your quick reply

Sorry I did not want to close it.


•Yes that could be right. that got better with matching line 464

•The others should not break because the default value is callback_query

**Comment by windkh** [comment]
I will merge your changes after the vacation... stay tuned

**Comment by MatthiasHunziker** [comment]
I found another error on line 530 today.
it should be type: "channel_post" not type: "edited_message".

Sorry I'm not a very good programmer because I'm not very experienced maybe there are more mistakes.

**Comment by windkh** [comment]
No problem. Could you add the fixes to the pullrequest?

**Comment by windkh** [comment]
1. I am currently reviewing your changes and there are plenty of things to discuss:
- the callback query node will have to be renamed to event node or something like that which makes it incompatible

2. Line 498: I think this id is useless as this is an "inline_query"
 
3. Line 507: Should we implement the auto answer here, too?

4. "inline_query" must also be implemented in the out node to be able to answer it explicitly

5. Line 548: Formatting is damaged somehow from that line on.

6. are there further events we should provide?

7. Examples and Documentations needs to be updated

I will merge your changes and then I will do the adaptions on my own.

**Pull request merged**
