### PR TITLE
2 fixes / 2 features

### PR DESCRIPTION
**Pull request by illegalentity**
- commit 1: just unified the line endings / trailing white spaces... it's pretty annoying to always see changes that are not really one

- commit 2: self explanatory. issue is linked
- commit 3: self explanatory. issue is linked

- commit 4 (no auth): this way you can still use a command node to handle the authentication process. I attached an example.

- commit 5 (multi responses): gives you the ability to easily create commands that take more than one answer. I added an example of a very simple calculator.

---

No Auth Command Node => Login Example
```
[{"id":"5f8976e0.1b3248","type":"telegram command","z":"5ee6bd01.28faa4","name":"","command":"/login","bot":"e84499ee.ca03c8","strict":false,"hasresponse":true,"multiresponse":false,"noauth":true,"x":1510,"y":4780,"wires":[["526e7efe.27b27"],["dbb802cf.eb87c"]]},{"id":"526e7efe.27b27","type":"function","z":"5ee6bd01.28faa4","name":"intro","func":"var username = msg.originalMessage.from.username;\nmsg.payload.type = \"message\";\nmsg.payload.content = \"Please insert the password!\";\nreturn msg;","outputs":1,"noerr":0,"x":1650,"y":4760,"wires":[["ee35bdc7.b7304"]],"outputLabels":["already loged in","not loged in yet"]},{"id":"ee35bdc7.b7304","type":"telegram sender","z":"5ee6bd01.28faa4","name":"","bot":"22516488.21949c","x":1830,"y":4780,"wires":[[]]},{"id":"dbb802cf.eb87c","type":"function","z":"5ee6bd01.28faa4","name":"auth","func":"var password = (msg.payload.content || \"\").trim();\nvar username = msg.originalMessage.from.username;\n\nmsg.payload.type = \"message\";\n\n// success\nif (password === \"123\") {\n    \n    var config = global.get(\"TelegramBotConfig\") || {};\n    msg.payload.content = \"Correct! Welcome...\";\n    \n    if (!config.users) {\n        config.users = [];\n    }\n    \n    if (config.users.indexOf(username) === -1) {\n        config.users.push(username);\n        global.set(\"TelegramBotConfig\", config);\n    }\n}\n\n// wrong password\nelse {\n    msg.payload.content = \"Nope... thats not correct!\";\n}\n\nreturn msg;\n","outputs":1,"noerr":0,"x":1650,"y":4800,"wires":[["ee35bdc7.b7304"]],"outputLabels":["","users changed"]},{"id":"e84499ee.ca03c8","type":"telegram bot","z":"","botname":"Dummy Bot","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false},{"id":"22516488.21949c","type":"telegram bot","z":"","botname":"Alarm (r7u235k_bot)","usernames":"{global.get(\"TelegramBotConfig\").users}","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":true}]
```

---

Multi Response Command => Calculator Example
```
[{"id":"827d72fc.c58f2","type":"function","z":"5ee6bd01.28faa4","name":"ask for operator","func":"msg.payload.type = 'message';\nmsg.payload.content = 'Choose an operation';\nmsg.payload.options = {\n    reply_to_message_id : msg.payload.messageId,\n    reply_markup: JSON.stringify({\n        keyboard: [\n            [\"+\", \"*\"], [\"-\", \"/\"]\n        ],\n        resize_keyboard: true,\n        one_time_keyboard: true\n    }),\n}\nreturn [ msg ];\n","outputs":"1","noerr":0,"x":760,"y":4780,"wires":[["81773f6e.9ace8"]]},{"id":"b4047462.728f38","type":"telegram command","z":"5ee6bd01.28faa4","name":"","command":"/calc","bot":"22516488.21949c","strict":false,"hasresponse":true,"multiresponse":true,"noauth":true,"x":90,"y":4800,"wires":[["827d72fc.c58f2"],["b0fd5ce3.e3a0d"]]},{"id":"81773f6e.9ace8","type":"telegram sender","z":"5ee6bd01.28faa4","name":"send question","bot":"22516488.21949c","x":940,"y":4780,"wires":[[]]},{"id":"b0fd5ce3.e3a0d","type":"function","z":"5ee6bd01.28faa4","name":"switch step","func":"var opt = flow.get(\"telegram_calculator\") || {};\n\nswitch (opt.step) {\n    default:\n        return [msg, null, null, null];\n    case 2:\n        return [null, msg, null, null];\n    case 3:\n        return [null, null, msg, null];\n    case 4:\n        return [null, null, null, msg];\n}\n","outputs":4,"noerr":0,"x":250,"y":4880,"wires":[["49dc6c8b.0b5cc4"],["f53975e8.229028"],["7e82c75b.42d878"],["2f6a68d4.80b7b8"]],"outputLabels":["operator","first number","sec number","summary"]},{"id":"95398fa9.6ef28","type":"telegram sender","z":"5ee6bd01.28faa4","name":"send question","bot":"22516488.21949c","x":940,"y":4820,"wires":[[]]},{"id":"49dc6c8b.0b5cc4","type":"function","z":"5ee6bd01.28faa4","name":"validate operator","func":"var op = (msg.payload.content || \"\").trim();\n\nif ([\"+\", \"-\", \"*\", \"/\"].indexOf(op) !== -1) {\n    var opt = flow.get(\"telegram_calculator\") || {};\n    opt.operator = op;\n    opt.step = 2;\n    flow.set(\"telegram_calculator\", opt);\n    return [msg, null];\n} else {\n    return [null, msg];\n}\n","outputs":2,"noerr":0,"x":490,"y":4820,"wires":[["1779a415.15296c"],["827d72fc.c58f2"]],"outputLabels":["valid","invalid"]},{"id":"1779a415.15296c","type":"function","z":"5ee6bd01.28faa4","name":"ask for first nr","func":"msg.payload.type = 'message';\nmsg.payload.content = 'Insert first number';\nmsg.payload.options = {\n    reply_to_message_id : msg.payload.messageId,\n}\nreturn [ msg ];\n","outputs":1,"noerr":0,"x":760,"y":4820,"wires":[["95398fa9.6ef28"]]},{"id":"f53975e8.229028","type":"function","z":"5ee6bd01.28faa4","name":"validate first number","func":"var value = (msg.payload.content || \"\").trim();\n\nif (!isNaN(value)) {\n    var opt = flow.get(\"telegram_calculator\") || {};\n    opt.first_number = value;\n    opt.step = 3;\n    flow.set(\"telegram_calculator\", opt);\n    return [msg, null];\n} else {\n    return [null, msg];\n}\n","outputs":2,"noerr":0,"x":480,"y":4860,"wires":[["298e5534.4594aa"],["1779a415.15296c"]],"outputLabels":["valid","invalid"]},{"id":"298e5534.4594aa","type":"function","z":"5ee6bd01.28faa4","name":"ask for sec nr","func":"msg.payload.type = 'message';\nmsg.payload.content = 'Insert second number';\nmsg.payload.options = {\n    reply_to_message_id : msg.payload.messageId,\n}\nreturn [ msg ];\n","outputs":1,"noerr":0,"x":760,"y":4860,"wires":[["cec451ec.0938c"]]},{"id":"cec451ec.0938c","type":"telegram sender","z":"5ee6bd01.28faa4","name":"send question","bot":"22516488.21949c","x":940,"y":4860,"wires":[[]]},{"id":"7e82c75b.42d878","type":"function","z":"5ee6bd01.28faa4","name":"validate sec number","func":"var value = (msg.payload.content || \"\").trim();\n\nif (!isNaN(value)) {\n    var opt = flow.get(\"telegram_calculator\") || {};\n    opt.sec_number = value;\n    opt.step = 4;\n    flow.set(\"telegram_calculator\", opt);\n    return [msg, null];\n} else {\n    return [null, msg];\n}\n","outputs":2,"noerr":0,"x":480,"y":4900,"wires":[["c326f073.c3488"],["298e5534.4594aa"]],"outputLabels":["valid","invalid"]},{"id":"c326f073.c3488","type":"function","z":"5ee6bd01.28faa4","name":"show summary","func":"var opt = flow.get(\"telegram_calculator\") || {};\n\nmsg.payload.type = 'message';\n\nvar result = eval(opt.first_number + \" \" + opt.operator + \" \" + opt.sec_number);\n\nmsg.payload.content = opt.first_number + \" \" +\n    opt.operator + \" \" + opt.sec_number + \" = \" + result;\n    \nmsg.payload.options = {\n    reply_to_message_id : msg.payload.messageId,\n    reply_markup: JSON.stringify({\n        keyboard: [\n            [\"Continue\"], [\"Cancel\"]\n        ],\n        resize_keyboard: true,\n        one_time_keyboard: true\n    }),\n}\nreturn [ msg ];\n","outputs":1,"noerr":0,"x":760,"y":4900,"wires":[["3a933e6e.f55ef2"]]},{"id":"3a933e6e.f55ef2","type":"telegram sender","z":"5ee6bd01.28faa4","name":"send question","bot":"22516488.21949c","x":940,"y":4900,"wires":[[]]},{"id":"2f6a68d4.80b7b8","type":"function","z":"5ee6bd01.28faa4","name":"continue/cancel","func":"var value = (msg.payload.content || \"\").trim().toLowerCase();\nflow.set(\"telegram_calculator\", null);\nif (value === \"continue\") {\n    return [msg, null];\n} else {\n    msg.payload.username = msg.originalMessage.from.username;\n    return [null, msg];\n}\n","outputs":2,"noerr":0,"x":500,"y":4940,"wires":[["827d72fc.c58f2"],["cbe9c21.800de4"]],"outputLabels":["continue","cancel"]},{"id":"cbe9c21.800de4","type":"telegram exit","z":"5ee6bd01.28faa4","name":"","bot":"22516488.21949c","x":750,"y":4940,"wires":[]},{"id":"22516488.21949c","type":"telegram bot","z":"","botname":"Alarm (r7u235k_bot)","usernames":"{global.get(\"TelegramBotConfig\").users}","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":true}]
```

### CODE REVIEW

**Comment by windkh** [comment]
Can you move the examples to the examples folder? 
Please adapt the readme so that you are under the credits section an then a description in the command node chapter would be nice. Thanks in advance

**Comment by daevidpreis** [comment]
Sure. I'll do that tomorrow

**Comment by daevidpreis** [comment]
Sorry... been so busy I totally forgot.
Added the examples and updated the readme.

**Comment by windkh** [comment]
Thanks ... don't worry, we are all busy ;)

**Comment by windkh** [comment]
Hi @daevidpreis ... sorry, but I can't merge all of your changes.

I will make my comments to your commits:
commit 1: just unified the line endings / trailing white spaces... it's pretty annoying to always see changes that are not really one
--> yes that would be helpful. 

commit 2: self explanatory. issue is linked
--> yes

commit 3: self explanatory. issue is linked
--> yes

commit 4 (no auth): this way you can still use a command node to handle the authentication process. I attached an example.
--> This is another pull request with a different story. than the previous ones

commit 5 (multi responses): gives you the ability to easily create commands that take more than one answer. I added an example of a very simple calculator.
--> I am not sure if that makes it more complicated: this is a separate pull request

**Pull request closed without merging**
