### PR TITLE
updated icons + .gitignore

### PR DESCRIPTION
**Pull request by bonastreyair**
# Icon redesign
What do you think about this proposed redesigned icons?

## Old version
Screenshot 2020-04-14 at 23 10 21

## New version
Screenshot 2020-04-14 at 23 08 29

### CODE REVIEW

**Comment by windkh** [comment]
The icons look way bettdr!

**Comment by bonastreyair** [comment]
> Why *.DS is gitignore?

Because I use MacOSX and it generates those kind of files automatically. I also added `node-modules` folder since when I test the node locally this folder also creates automatically...

**Comment by bonastreyair** [comment]
I'm preparing a improvement on changelog, hope you like it also.

**Comment by windkh** [comment]
> > Why *.DS is gitignore?
> 
> Because I use MacOSX and it generates those kind of files automatically. I also added `node-modules` folder since when I test the node locally this folder also creates automatically...

Then please remove it...

**Comment by bonastreyair** [comment]
OK I will not add it on next PR no problem

**Comment by windkh** [comment]
... I also thought about adding my visual code project files, but that is way too specific

**Comment by windkh** [comment]
> I'm preparing an improvement on the changelog in a new PR, and some refinements on the `README` file, hope you like them also.

You mean a table?

**Comment by windkh** [comment]
The whole readme should be reworked but I am too lazy=busy for that

**Comment by bonastreyair** [comment]
> ... I also thought about adding my visual code project files, but that is way too specific

I meant that I added `node-modules` folder in the .gitignore so that it does not load into GitHub by mistake :)

**Comment by bonastreyair** [comment]
> > I'm preparing an improvement on the changelog in a new PR, and some refinements on the `README` file, hope you like them also.
> 
> 
> 
> You mean a table?

Well not table just reworks, and a new changelog file.

Check the new PR [#107](https://github.com/windkh/node-red-contrib-telegrambot/pull/107)!

**Pull request merged**
