### PR TITLE
Catch sender errors to msg.error

### PR DESCRIPTION
**Pull request by dvv**
Please, consider applying

### CODE REVIEW

**Comment by windkh** [comment]
Sorry for delay, I will do the merge this evening

**Comment by windkh** [comment]
Hm I am not sure  if it would be better to send the exceptions on a different output. How should the exceptions be handled by the following node? How did you do this?

**Comment by windkh** [comment]
Thanx

**Comment by dvv** [comment]
I believe in the following function block:
```
if (msg.error) {
  // sender errored
} else {
  // sender was good
}
```
Even a switch block may separate errors on `msg.errors`

**Pull request merged**
