### PR TITLE
Added feature sendMediaGroup

### PR DESCRIPTION
**Pull request by MK-2001**
I just created a function to enable the featue to send MediaGroup. This is needed to send photos as a album.

### CODE REVIEW

**Comment by windkh** [comment]
Thanks for providing this. If we are able to send that kind of messages, then we also need:
- the type in the receiver group
- an updated readme
- an example flow that illustrates the usage
Will you provide that also, or should I do the neccessary changes?

**Comment by MK-2001** [comment]
Hi Karl-Heinz,

i will provide it as soon as possible. Hopeful this wee. I will start a 
new pull request. Is it fine for you?

Grüße & Kind regards
Marcus



Am 2019-04-01 21:55, schrieb Karl-Heinz Wind:

**Comment by windkh** [comment]
Hi Markus
Danke super!
Gr kh

Gesendet mit der WEB.DE iPad App

Am 02.04.19 um 08:30 schrieb Marcus K

**Comment by windkh** [comment]
should be included in version 5.4.0
thanks alot

**Pull request merged**
