### PR TITLE
add cosmetic changes, icon, colour, info, move examples

### PR DESCRIPTION
**Pull request by dceejay**
Hi, 

this pull request updates the node icon and colour to better match default Telegram colours. 

Also adds more info to the info sidebar to try to help (though I admit I don't fully understand the callback or reply nodes...

Finally it moves the examples to the examples directory so they appear under Menu - Import - Examples within the editor.

### CODE REVIEW

**Comment by windkh** [comment]
Hi,
thank you very much for cleaning up the files.

**Comment by windkh** [comment]
version 2.5.2 contains your changes. Thanks alot.

**Comment by dceejay** [comment]
Thanks for merging.  Note: one of the examples was just called example - that could probably be renamed slightly more appropriately :-) 
and the info for reply and callback could/should be better if I understood how they should be used !

**Comment by windkh** [comment]
Example flow is renamed now.

Well, the concept of the reply node is not easy to explain in a short sentence (at least for me).
If someone sent a message like „What do you mean?“ to the chat, there are two ways for you to respond to it. 
1. Write your own message which will apear as separate message right below the first one in the chat window.
2. Right–click on the first message and choose „answer“ from the popup. Which creates a different type of message (it includes the original message in quotes).

The reply node is triggered for the second case. It does not get triggered for every message but only when someone answered to the specified one. This messageId can be retrieved from the output of the sender node, after the message was sent away. That‘s the reason why I named the parameter sentMessageId.

Well, this kind of node allows you to create a simple question and answer flow...

**Comment by dceejay** [comment]
ah ok - think I got it.
(does make me wonder if these different sub options ought to be selectable options within a single receive node - and likewise for the output - but will leave that for a separate discussion.

**Comment by windkh** [comment]
I agree

**Pull request merged**
