### PR TITLE
Allow "blob" messages to autodownload

### PR DESCRIPTION
**Pull request by dvv**
Receiver: if a message is downloadable and `saveDataDir` option is set then download the message to local file and provide its path as `.path` key of output message.

Please, consider applying.

### CODE REVIEW

**Comment by windkh** [comment]
Thanx for contributing this.

**Comment by dvv** [comment]
Would you publish it to npm so that I flush local changes? Thank you

**Comment by windkh** [comment]
Done

**Comment by dvv** [comment]
Thank you!

**Pull request merged**
